2025-06-18 00:19:43,451 - ERROR - Error renaming file PYT3_02912_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_cal.pdf'
2025-06-18 00:19:43,465 - ERROR - Error renaming file PYT3_02912_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_pm.pdf'
2025-06-18 00:19:43,497 - ERROR - Error renaming file PYT3_02913_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_cal.pdf'
2025-06-18 00:19:43,519 - ERROR - Error renaming file PYT3_02913_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_pm.pdf'
2025-06-18 00:19:43,555 - ERROR - Error renaming file PYT3_04921_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_cal.pdf'
2025-06-18 00:19:43,578 - ERROR - Error renaming file PYT3_04921_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_pm.pdf'
2025-06-18 00:19:43,609 - ERROR - Error renaming file PYT3_04922_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_cal.pdf'
2025-06-18 00:19:43,632 - ERROR - Error renaming file PYT3_04922_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_pm.pdf'
2025-06-18 00:19:43,653 - ERROR - Error renaming file PYT3_05967_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_cal.pdf'
2025-06-18 00:19:43,689 - ERROR - Error renaming file PYT3_05967_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_pm.pdf'
2025-06-18 00:19:43,727 - ERROR - Error renaming file PYT3_06536_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_cal.pdf'
2025-06-18 00:19:43,757 - ERROR - Error renaming file PYT3_06536_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_pm.pdf'
2025-06-18 00:19:43,788 - ERROR - Error renaming file PYT3_06569_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_cal.pdf'
2025-06-18 00:19:43,829 - ERROR - Error renaming file PYT3_06569_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_pm.pdf'
2025-06-18 00:19:43,868 - ERROR - Error renaming file PYT3_09071_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_cal.pdf'
2025-06-18 00:19:43,904 - ERROR - Error renaming file PYT3_09071_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_pm.pdf'
2025-06-18 00:27:01,144 - ERROR - Error renaming file PYT3_02912_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_cal.pdf'
2025-06-18 00:27:01,373 - ERROR - Error renaming file PYT3_02912_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_pm.pdf'
2025-06-18 00:27:01,592 - ERROR - Error renaming file PYT3_02913_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_cal.pdf'
2025-06-18 00:27:01,814 - ERROR - Error renaming file PYT3_02913_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_pm.pdf'
2025-06-18 00:27:02,043 - ERROR - Error renaming file PYT3_04921_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_cal.pdf'
2025-06-18 00:27:02,266 - ERROR - Error renaming file PYT3_04921_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_pm.pdf'
2025-06-18 00:27:02,491 - ERROR - Error renaming file PYT3_04922_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_cal.pdf'
2025-06-18 00:27:02,714 - ERROR - Error renaming file PYT3_04922_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_pm.pdf'
2025-06-18 00:27:02,937 - ERROR - Error renaming file PYT3_05967_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_cal.pdf'
2025-06-18 00:27:03,157 - ERROR - Error renaming file PYT3_05967_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_pm.pdf'
2025-06-18 00:27:03,380 - ERROR - Error renaming file PYT3_06536_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_cal.pdf'
2025-06-18 00:27:03,602 - ERROR - Error renaming file PYT3_06536_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_pm.pdf'
2025-06-18 00:27:03,826 - ERROR - Error renaming file PYT3_06569_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_cal.pdf'
2025-06-18 00:27:04,046 - ERROR - Error renaming file PYT3_06569_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_pm.pdf'
2025-06-18 00:27:04,274 - ERROR - Error renaming file PYT3_09071_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_cal.pdf'
2025-06-18 00:27:04,518 - ERROR - Error renaming file PYT3_09071_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_pm.pdf'
2025-06-18 00:28:05,125 - ERROR - Error renaming file PYT3_02912_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_cal.pdf'
2025-06-18 00:28:05,369 - ERROR - Error renaming file PYT3_02912_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02912_2025_pm.pdf'
2025-06-18 00:28:05,598 - ERROR - Error renaming file PYT3_02913_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_cal.pdf'
2025-06-18 00:28:05,831 - ERROR - Error renaming file PYT3_02913_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_02913_2025_pm.pdf'
2025-06-18 00:28:06,065 - ERROR - Error renaming file PYT3_04921_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_cal.pdf'
2025-06-18 00:28:06,293 - ERROR - Error renaming file PYT3_04921_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04921_2025_pm.pdf'
2025-06-18 00:28:06,527 - ERROR - Error renaming file PYT3_04922_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_cal.pdf'
2025-06-18 00:28:06,772 - ERROR - Error renaming file PYT3_04922_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_04922_2025_pm.pdf'
2025-06-18 00:28:07,013 - ERROR - Error renaming file PYT3_05967_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_cal.pdf'
2025-06-18 00:28:07,251 - ERROR - Error renaming file PYT3_05967_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_05967_2025_pm.pdf'
2025-06-18 00:28:07,475 - ERROR - Error renaming file PYT3_06536_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_cal.pdf'
2025-06-18 00:28:07,708 - ERROR - Error renaming file PYT3_06536_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06536_2025_pm.pdf'
2025-06-18 00:28:07,934 - ERROR - Error renaming file PYT3_06569_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_cal.pdf'
2025-06-18 00:28:08,178 - ERROR - Error renaming file PYT3_06569_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_06569_2025_pm.pdf'
2025-06-18 00:28:08,404 - ERROR - Error renaming file PYT3_09071_2025_cal.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_cal.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_cal.pdf'
2025-06-18 00:28:08,643 - ERROR - Error renaming file PYT3_09071_2025_pm.pdf: [WinError 2] The system cannot find the file specified: 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_pm.pdf' -> 'd:\\github\\forms-1\\py_test_ui\\REPORTS\\PYT3_09071_2025_pm.pdf'
2025-06-18 01:27:31,291 - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-18 01:27:31,292 - ERROR - Detailed traceback:
Traceback (most recent call last):
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-18 01:29:06,525 - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-18 01:29:06,526 - ERROR - Detailed traceback:
Traceback (most recent call last):
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-18 01:33:47,258 - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-18 01:33:47,260 - ERROR - Detailed traceback:
Traceback (most recent call last):
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-18 01:33:50,214 - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-18 01:33:50,215 - ERROR - Detailed traceback:
Traceback (most recent call last):
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-18 01:46:13,700 - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-18 01:46:13,702 - ERROR - Detailed traceback:
Traceback (most recent call last):
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\mak_r\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
